// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
//import "dotenv/config";

import "dotenv/config";
import { defineConfig } from "prisma/config";

const databaseUrl = process.env["DATABASE_URL"];

if (!databaseUrl) {
  throw new Error("A variável de ambiente DATABASE_URL não foi definida.");
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});

//import { defineConfig } from "prisma/config";
//
//export default defineConfig({
//  schema: "prisma/schema.prisma",
//  migrations: {
//    path: "prisma/migrations",
//  },
//  datasource: {
//     url: databaseUrl,
//  },
//});
